# Site settings
title: Your Title
author: author
email:
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# Site URL NOTE: if your site is base on subdir /blog you should change base to "/blog"
domain: "http://yourdomain.github.io" # the domain URL for your site
base: ""  # the relative path that different with domain so you can test locally

# Source URL NOTE: end with / cause it's [URL + FILE]
w3c_url: "/w3c/"  # the base url of css js and images
images_url: "/w3c/images/" # the base url of post images
postfile: "/db/Postfile" # the Database
sitefile: "/db/Sitefile" # the Database

# pagination
page_size: 3

# comment settings
duoshuo_short_name: "sbys" # the user of user.domain.com
duoshuo_user_uid: "6324572809590735618" # the admin user uid
duoshuo_user_name: "xk" # the admin user name
duoshuo_max_depth: "2"  # the max_depth setting in duoshuo comments

# 3rd URL
duoshuo_url: "/w3c/duoshuo/embed.min.js" # the local duoshuo comment plugin, you can change it to remote "http://static.duoshuo.com/"
jquery_url: "http://cdn.bootcss.com/jquery/3.1.0/jquery.min.js" # use cdn
baiduTemplate_url: "/w3c/js/baiduTemplate.js" #use local
google_analytics_id: ""
baidu_tongji_id: ""

# Build Settings
excerpt_separator: "\n\n" # you can specify your own separator here, default is "\n\n" String
permalink: /:year/:month/:day/:title.html
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true # a newline in markdown text would be changed to <br>
gems:
  - jemoji    # enable the github emoji
version: 1.1.0

# Following is got in Github Help With Configuring Jekyll

# Github Page Default Settings which you can override:
# kramdown:
#   input: GFM
#   hard_wrap: false
# gems:
#   - jekyll-coffeescript
#   - jekyll-paginate

# Github Page override the following settings which you cannot change:
# lsi: false
# safe: true
# source: [your repo's top level directory]
# incremental: false
# highlighter: rouge
# gist:
#  noscript: false
# kramdown:
#  math_engine: mathjax
